### ISSUE TITLE
按钮使用 Grid 来自适应窗口大小

### ISSUE THREAD

**Issue by SYBass** [Ad-closeNN/PCL2-home-page#15]
### 检查项

- [X] 我确定这不是 [新功能提案](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E6%96%B0%E5%8F%8D%E9%A6%88&projects=&template=feature.yml) 类型的 Issue，这是 优化 类型的 Issue。
- [X] 我确定这不是 [Bug 反馈](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?projects=&template=bug9.yml) 类型的 Issue，这是 优化 类型的 Issue。

### 描述

这是你的源代码
![QQ截图20240323093622](https://github.com/Ad-closeNN/PCL2-home-page/assets/125178599/a0f6d768-442f-4b45-a462-3b56264eb926)
![QQ截图20240323093822](https://github.com/Ad-closeNN/PCL2-home-page/assets/125178599/fc2d0c78-722c-443a-afa3-82954e829153)

我之前的代码：
![QQ截图20240323093925](https://github.com/Ad-closeNN/PCL2-home-page/assets/125178599/9f5ba13f-eed4-4d12-90b7-469773446b3f)

你可以用grid控件来写会更好看

### 原因

提高主页质量，增强用户体验程度awa

**Comment by Ad-closeNN** [comment]
要不就这样？我没啥好办法了
![image](https://github.com/Ad-closeNN/PCL2-home-page/assets/103355026/8102359d-b103-4c14-b8ba-df51bcd21127)

**Comment by Ad-closeNN** [comment]
貌似...MyistItem不用grid?改个标题吧.
