### ISSUE TITLE
无法打开其他主页的预览主页

### ISSUE THREAD

**Issue by SYBass** [Ad-closeNN/PCL2-home-page#18]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Ad-closeNN/PCL2-home-page/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。
- [X] 我确定这不是 [新功能提案](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E6%96%B0%E5%8F%8D%E9%A6%88&projects=&template=feature.yml) 类型的 Issue，这是 Bug 类型的 Issue。
- [X] 我确定这不是 [优化建议](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?assignees=&labels=%C2%B7+%E4%BC%98%E5%8C%96%2C%E6%96%B0%E5%8F%8D%E9%A6%88&projects=&template=ch.yml) 类型的 Issue，这是 Bug 类型的 Issue。

### 描述

无法打开预览主页（除了信标的）

### 重现步骤

点击【预览主页】

**Comment by Ad-closeNN** [comment]
能啊?你咋不行
顺便提一嘴 龙猫那些啥的没有提供直链的但是又有github仓库的我直接用加速cdn的 难道是你网络环境的问题？
还有wemusr的主页确实不能用 下次改（

**Comment by Ad-closeNN** [comment]
wemusr的不好搞，删除吧（
