### ISSUE TITLE
联机界面回归

### ISSUE THREAD

**Issue by Aminos114514** [Ad-closeNN/PCL2-home-page#19]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Ad-closeNN/PCL2-home-page/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。
- [X] 我确定这不是 [新功能提案](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E6%96%B0%E5%8F%8D%E9%A6%88&projects=&template=feature.yml) 类型的 Issue，这是 Bug 类型的 Issue。
- [X] 我确定这不是 [优化建议](https://github.com/Ad-closeNN/PCL2-home-page/issues/new?assignees=&labels=%C2%B7+%E4%BC%98%E5%8C%96%2C%E6%96%B0%E5%8F%8D%E9%A6%88&projects=&template=ch.yml) 类型的 Issue，这是 Bug 类型的 Issue。

### 描述

联机界面通过其他方式可以再次激活

### 重现步骤

1、使用自定义主界面文件编辑主界面
2、输入”<local:MyButton Grid.Column="0" Height="35" Margin="0,0,10,10" ColorType="Red"
          Text="XXXX”  EventType="切换页面" ToolTip="跳转至“设置”" EventData="2|1"/>”
3、载入主界面
4、使用这个创建的按钮
5，来到了联机界面
![7F604B2F73257009B7367D1827247B8C](https://github.com/user-attachments/assets/38542ec4-05a7-4e7b-b3ed-29e6f99e3b1e)
![Uploading 2363883D5B29F9E454FE45790A992940.png…]()

**Comment by Ad-closeNN** [comment]
Duplicate of #4859
