### ISSUE TITLE
快捷方式已经无法使用

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Ad-closeNN/PCL2-home-page#8]
点击时 PCL 反馈
![image](https://github.com/Ad-closeNN/PCL2-home-page/assets/109946426/d8d96e48-8665-497a-a575-43746016988b)
其他链接同理

**Comment by Ad-closeNN** [comment]
这个嘛...没装对应的应用是打不开的...
比如安装osu后osu就会自动注册osu://到注册表（其他软件同理）就可以达到直接启动

mfn的主页也有同样的问题（启动基岩版）
![image](https://github.com/Ad-closeNN/PCL2-home-page/assets/103355026/765df594-5a7e-41a9-b8fc-e6e7394f76ae)

**Comment by JingHai-Lingyun** [comment]
Minecraft 也这样...
我手动 Win+R 能运行

**Comment by Ad-closeNN** [comment]
那就看着办吧，贴个提示条就行了.jpg

**Comment by JingHai-Lingyun** [comment]
行（

**Comment by JingHai-Lingyun** [comment]
好了，现在限制了协议，都没用了，删掉吧 @Ad-closeNN

**Comment by Ad-closeNN** [comment]
？6你还真的看得上这个存储库

留个MC吧至少MC能打得开

**Comment by JingHai-Lingyun** [comment]
嗯，在重构 MFn 的 Market，正好就过来看到了这 Issue
